### ISSUE TITLE
Abstraction layer for font project files

### ISSUE THREAD

**Issue by felipesanches** [simoncozens/flux#4]
@simoncozens, I'm interested in your approach for an abstraction layer for font projects. Do you already have code for that in some repo? It is not clear to me if you already have a thirdparty python library for that abstraction layer, or if you are planning to implement one. This could be useful for font source checks on FontBakery

**Comment by simoncozens** [comment]
There is some code [here](https://github.com/simoncozens/fontFeatures/blob/master/fontFeatures/fontProxy.py) and [here](https://github.com/simoncozens/glyphtools) but it doesn’t quite do everything I want, so this week I am starting again with an approach based on fontParts. Nothing checked in yet though.

**Comment by simoncozens** [comment]
This is now [babelfont](https://github.com/simoncozens/babelfont), and Flux now uses it!

**Comment by felipesanches** [comment]
great! :-D
