### ISSUE TITLE
flux opens file requester on Mac, don't know what to do

### ISSUE THREAD

**Issue by pgundlach** [simoncozens/flux#5]
The Flux app opens a file requester, but there is no information what file to open.

I'd expect some hint or documentation somewhere. I can only create new directories. Is the file requester looking for a specific file or is it looking for a place to save files?

**Comment by simoncozens** [comment]
Thanks for trying this, and I'm sorry that's confusing. This is why it's a UX preview - currently the UX is bad and needs improving!

It's looking for a font to open, and you need to give it a .glyphs file.
